# -ftree-vectorize is on by default when -O3
# -ffast-math is for -ftree-vectorize
env = Environment(
                  CXX = '/opt/local/bin/g++-mp-4.5',
                  CPPFLAGS = ' -std=c++0x -pipe '
                  #+ ' -g'
                  + ' -O3 -march=core2 -ffast-math -ftree-vectorize' # -ftree-vectorizer-verbose=1'
                  + ' -fopenmp'
                  + ' -Dcimg_display=0 -fno-tree-pre -Dcimg_use_openmp' # for CImg
                  ,
                  CPPPATH=['.'], #-I, include directories
                  LINKFLAGS=['-framework', 'OpenGL', '-framework', 'GLUT', '-fopenmp']
                 )

# Parallel build
import os
num_cpu = int(os.environ.get('NUM_CPU', 2))
SetOption('num_jobs', num_cpu)
print "running with -j", GetOption('num_jobs')

srcs = ['hw5.cpp', 'ray_tracer.cpp', 'object.cpp', 'triangle.cpp', 'polyhedron.cpp', 'bsp_tree.cpp', 'octree.cpp', 'scene.cpp', 'obj_file.cpp']
prog = env.Program('hw5', srcs)

env.Command('tags', Glob('*.cpp *.h'), 'echo CTAGS && ctags *')

# Run
import os
os.system('ctags *')
#os.system('open -a Terminal.app hw5')
