env = Environment(
                  CXX = '/opt/local/bin/g++-mp-4.5',
                  CPPFLAGS = ' -std=c++0x -O3 -pipe -march=native -ffast-math -ftree-vectorize -ftree-vectorizer-verbose=1 -fopenmp',
                  CPPPATH=['.'], #-I, include dirs
                  LINKFLAGS=['-framework', 'OpenGL', '-framework', 'GLUT', '-fopenmp']
                 )

srcs = ['hw5.cpp', 'ray_tracer.cpp', 'object.cpp', 'triangle.cpp', 'polyhedron.cpp']
prog = env.Program('hw5', srcs)
#env.AddPostAction(prog, prog.abspath)

# Run
import os
os.system('ctags *')
#os.system('open -a Terminal.app hw5')
